wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.3
    framework: huggingface
    huggingface_version: 4.23.1
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1666282027.211717
    t:
      1:
      - 1
      - 11
      - 49
      - 55
      2:
      - 1
      - 11
      - 49
      - 55
      3:
      - 19
      - 23
      4: 3.9.13
      5: 0.13.3
      6: 4.23.1
      8:
      - 1
      - 5
device:
  desc: null
  value: cuda
guidance_scale:
  desc: null
  value: 7.5
image_height:
  desc: null
  value: 512
image_width:
  desc: null
  value: 768
model_path_clip:
  desc: null
  value: openai/clip-vit-large-patch14
model_path_diffusion:
  desc: null
  value: CompVis/stable-diffusion-v1-4
model_precision_type:
  desc: null
  value: fp16
prompt:
  desc: null
  value: A photo of a Person with flower headpiece and elegant jewels
prompt_edit:
  desc: null
  value: A photo of a Person with butterfly headpiece and elegant jewels
prompt_edit_spatial_end:
  desc: null
  value: 0.8
prompt_edit_spatial_start:
  desc: null
  value: 0.0
prompt_edit_token_weights:
  desc: null
  value:
  - - 7
    - 4
prompt_edit_tokens_end:
  desc: null
  value: 1.0
prompt_edit_tokens_start:
  desc: null
  value: 0.0
seed:
  desc: null
  value: 98374234
steps:
  desc: null
  value: 50
