wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.3
    framework: huggingface
    huggingface_version: 4.23.1
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1666281446.635009
    t:
      1:
      - 1
      - 11
      - 49
      - 55
      2:
      - 1
      - 11
      - 49
      - 55
      3:
      - 2
      - 19
      - 23
      4: 3.9.13
      5: 0.13.3
      6: 4.23.1
      8:
      - 1
      - 5
device:
  desc: null
  value: cuda
model_path_clip:
  desc: null
  value: openai/clip-vit-large-patch14
model_path_diffusion:
  desc: null
  value: CompVis/stable-diffusion-v1-4
model_precision_type:
  desc: null
  value: fp16
